"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, HeartIcon, StarIcon } from "@/components/icons";
import { AvailabilityNotice, SourceBadge } from "@/components/travel-readiness";
import { atolls, experiences, guides, images, properties, Property } from "@/lib/data";

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="page-hero" data-reveal><div className="page-wrap page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>;
}

function PropertyCard({ property }: { property: Property }) {
  const [saved, setSaved] = useState(false);
  return <article className="stay-card"><div className="stay-image" style={{ "--card-image": `url(${property.image})` } as React.CSSProperties}><span className="stay-badge">{property.badge}</span><button className="image-heart" type="button" aria-label="Toggle wishlist" onClick={() => setSaved(!saved)}><HeartIcon filled={saved} /></button></div><div className="stay-body"><div className="stay-meta"><span>{property.location}</span><span><StarIcon size={11} /> {property.rating}</span></div><div className="card-source-row"><SourceBadge source="sample" /></div><h3>{property.name}</h3><p>{property.description}</p><div className="stay-footer"><Link href={`/stay/${property.slug}`}>Explore stay <ArrowUpRight size={13} /></Link><span>From ${property.price}</span></div></div></article>;
}

export function StayDirectory({ title = "Stay somewhere extraordinary." }: { title?: string }) {
  const [query, setQuery] = useState("");
  const [active, setActive] = useState("All stays");
  const [map, setMap] = useState(false);
  const [sortBy, setSortBy] = useState("recommended");
  const filters = ["All stays", "Resorts", "Guesthouses", "Overwater", "All-inclusive", "Under $150"];
  const shown = useMemo(() => {
    const filtered = properties.filter((property) => {
      const matchesQuery = `${property.name} ${property.location} ${property.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase());
      const matchesType = active === "All stays" || (active === "Resorts" && property.kind === "Resort") || (active === "Guesthouses" && property.kind === "Guesthouse") || (active === "Overwater" && property.tags.includes("Overwater")) || (active === "All-inclusive" && property.tags.includes("All-inclusive")) || (active === "Under $150" && property.price < 150);
      return matchesQuery && matchesType;
    });
    return [...filtered].sort((a, b) => sortBy === "price-low" ? a.price - b.price : sortBy === "price-high" ? b.price - a.price : b.rating - a.rating);
  }, [query, active, sortBy]);
  return <><PageIntro eyebrow="CURATED STAYS" title={title} description="Compare the places that make island time feel effortless — from iconic overwater villas to guesthouses on the local islands." /><main className="page-main"><div className="page-wrap"><div className="directory-toolbar"><div className="filter-row">{filters.map((filter) => <button key={filter} className={`filter-chip ${active === filter ? "active" : ""}`} onClick={() => setActive(filter)}>{filter}</button>)}</div><div className="directory-actions"><label className="search-inline"><span className="sr-only">Search stays</span><input className="input" placeholder="Search stays or islands" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select className="input results-sort" aria-label="Sort stays" value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="recommended">Recommended</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><button className={`view-toggle ${!map ? "active" : ""}`} onClick={() => setMap(false)}>List</button><button className={`view-toggle ${map ? "active" : ""}`} onClick={() => setMap(true)}>Map</button></div></div>{map ? <div className="map-placeholder"><div className="map-card"><span className="eyebrow">OpenStreetMap view</span><h2>Island stays, at a glance.</h2><p>Map integration is ready for Mapbox or Leaflet when live coordinates are connected.</p><Link href="#results" className="button button-teal button-small">Back to list <ArrowRight size={13} /></Link></div><div className="map-dots"><span /><span /><span /><span /><span /></div></div> : <><div className="results-toolbar" id="results"><div><strong>{shown.length} stays to explore</strong><span className="results-muted">Sample inventory · prices shown in USD</span></div><AvailabilityNotice source="sample" /></div>{shown.length ? <div className="directory-grid">{shown.map((property) => <PropertyCard key={property.slug} property={property} />)}</div> : <div className="empty-state">No stays match this search yet. Try another island, style or budget.</div>}</>}</div></main></>;
}

export function StayDetail({ property }: { property: Property }) {
  const [requested, setRequested] = useState(false);
  return <><PageIntro eyebrow={`${property.kind.toUpperCase()} · SAMPLE LISTING`} title={property.name} description={`${property.location} · ${property.transfer}. A representative listing layout for the Maldives.org booking-ready directory.`} /><main className="page-main" data-reveal><div className="page-wrap detail-layout"><div><div className="detail-hero-image" style={{ backgroundImage: `url(${property.image})` }} /><div className="detail-card detail-overview"><div className="stay-meta"><span>{property.location}</span><span><StarIcon size={11} /> {property.rating} guest rating</span></div><h2>An easier way to do island time.</h2><p>{property.description} This sample property uses the same calm, image-led system as the homepage while leaving space for partner data, room types, transfer notes and verified availability.</p><div className="detail-list"><div><strong>Transfer</strong><span>{property.transfer}</span></div><div><strong>From</strong><span>${property.price} / night</span></div><div><strong>Best for</strong><span>{property.tags.slice(0, 2).join(" · ")}</span></div><div><strong>Booking mode</strong><span>Request to book</span></div></div><h2>What to expect</h2><p>Stay details, meal plans, amenities, policies and partner-confirmed availability will live here. Until a live partner feed is connected, every listing is clearly marked as sample inventory.</p></div></div><aside className="detail-card sticky-card"><div className="price-line"><div><strong>${property.price}</strong><span> / night</span></div><span>Charged in USD</span></div><label className="field-label" htmlFor="detail-check-in">Check in</label><input id="detail-check-in" className="input" type="date" /><label className="field-label" htmlFor="detail-check-out">Check out</label><input id="detail-check-out" className="input" type="date" /><label className="field-label" htmlFor="detail-guests">Guests</label><select id="detail-guests" className="input" defaultValue="2 guests"><option>2 guests</option><option>3 guests</option><option>4 guests</option></select><button className="button button-teal full-button" type="button" style={{ marginTop: 18 }} onClick={() => setRequested(true)}>{requested ? "Request noted" : "Request to book"} <ArrowRight size={14} /></button><Link className="button button-ghost button-dark full-button" href={`/booking?type=stay&slug=${property.slug}`} style={{ marginTop: 8 }}>Open booking flow <ArrowRight size={14} /></Link><div className="note-box" role={requested ? "status" : undefined}>{requested ? "Your request is captured for this demo. A partner would confirm availability next." : "A partner will confirm your request within 48 hours. No payment is taken in this demo."}</div></aside></div></main></>;
}

export function ExperienceDirectory() {
  return <><PageIntro eyebrow="BEYOND THE VILLA" title="Make the water your itinerary." description="Book a reef morning, a sunset sail or a local-island day — then bundle it into the trip you actually want to take." /><main className="page-main"><div className="page-wrap"><div className="directory-trust-row"><AvailabilityNotice source="sample" /><Link className="text-link" href="/how-it-works">How supplier data will work <ArrowRight size={13} /></Link></div><div className="experience-grid directory-experience-grid">{experiences.map((experience, index) => <Link href={`/experiences/${experience.slug}`} className="experience-tile" style={{ "--tile-image": `url(${experience.image})` } as React.CSSProperties} key={experience.slug}><div><span className="experience-category">{experience.category}</span><h3>{experience.name}</h3><p>{experience.duration} · From ${experience.price}</p><span className="experience-source">Sample inventory</span></div></Link>)}</div><div className="section-space"><div className="section-header"><div><span className="eyebrow">Travel by interest</span><h2>Small moments, big memories.</h2></div><p>Every experience is shown with the practical details that help you decide: timing, location, season and what is included.</p></div><div className="featured-grid">{experiences.slice(0, 3).map((experience) => <article className="detail-card experience-mini" key={experience.slug}><span className="eyebrow">{experience.category}</span><h3>{experience.name}</h3><p>{experience.description}</p><Link className="text-link" href={`/experiences/${experience.slug}`}>View details <ArrowRight size={13} /></Link></article>)}</div></div></div></main></>;
}

export function ExperienceDetail({ experience }: { experience: typeof experiences[number] }) {
  const [requested, setRequested] = useState(false);
  return <><PageIntro eyebrow={`${experience.category.toUpperCase()} · SAMPLE EXPERIENCE`} title={experience.name} description={experience.description} /><main className="page-main" data-reveal><div className="page-wrap detail-layout"><div><div className="detail-hero-image" style={{ backgroundImage: `url(${experience.image})` }} /><div className="detail-card detail-overview"><span className="eyebrow">Your day on the water</span><h2>Made for curious travellers.</h2><p>Meet your local guide, understand the conditions and take the pace that suits you. This sample experience page is ready for sessions, capacity, waivers, verified reviews and partner pricing.</p><div className="detail-list"><div><strong>Duration</strong><span>{experience.duration}</span></div><div><strong>From</strong><span>${experience.price} / person</span></div><div><strong>Pick-up</strong><span>Island or resort jetty</span></div><div><strong>Season</strong><span>Year-round, conditions permitting</span></div></div></div></div><aside className="detail-card sticky-card"><div className="price-line"><div><strong>${experience.price}</strong><span> / person</span></div></div><label className="field-label" htmlFor="experience-date">Choose a date</label><input className="input" id="experience-date" type="date" /><label className="field-label" htmlFor="experience-guests">Participants</label><select id="experience-guests" className="input" defaultValue="2"><option value="1">1 participant</option><option value="2">2 participants</option><option value="3">3 participants</option></select><button className="button button-sun full-button" type="button" style={{ marginTop: 18 }} onClick={() => setRequested(true)}>{requested ? "Spot requested" : "Request a spot"} <ArrowRight size={14} /></button><Link className="button button-ghost button-dark full-button" href={`/booking?type=experience&slug=${experience.slug}`} style={{ marginTop: 8 }}>Open booking flow <ArrowRight size={14} /></Link><div className="note-box" role={requested ? "status" : undefined}>{requested ? "Your interest is captured for this demo. Session details would be confirmed next." : "Session availability and final pricing are confirmed before payment."}</div></aside></div></main></>;
}

export function GuidesPage() {
  return <><PageIntro eyebrow="TRAVEL GUIDES" title="Go with a little more context." description="Useful notes for choosing an atoll, getting from the airport to the jetty and knowing what island life feels like before you arrive." /><main className="page-main"><div className="page-wrap article-list">{guides.map((guide) => <Link className="article-card" key={guide.slug} href={`/guides/${guide.slug}`}><div className="article-image" style={{ "--card-image": `url(${guide.image})` } as React.CSSProperties} /><div><span className="eyebrow">{guide.eyebrow}</span><h3>{guide.title}</h3><p>{guide.excerpt}</p><span className="article-read">{guide.read} <ArrowUpRight size={12} /></span></div></Link>)}</div></main></>;
}

export function GuideDetail({ guide }: { guide: typeof guides[number] }) {
  return <><PageIntro eyebrow={guide.eyebrow} title={guide.title} description={guide.excerpt} /><main className="page-main"><div className="page-wrap article-layout"><article className="detail-card longform"><div className="detail-hero-image" style={{ backgroundImage: `url(${guide.image})` }} /><p className="lead">The best Maldives trip is not just about where you stay. It is about the small decisions around weather, transfers, reef life and pace that make the whole week feel lighter.</p><h2>Start with the shape of your trip.</h2><p>Use this guide as a friendly starting point, then compare stays and routes once you know what matters most. Partner details, seasonal notes and live availability will be connected here as the directory grows.</p><h2>Three things to keep in mind</h2><div className="guide-points"><div><strong>01</strong><span>Leave time for the transfer. Island geography is part of the experience.</span></div><div><strong>02</strong><span>Ask what is included. A clear total is always better than a low headline price.</span></div><div><strong>03</strong><span>Choose the island rhythm you actually enjoy, not the one that looks best in a photo.</span></div></div></article><aside className="detail-card"><span className="eyebrow">Explore next</span><h2>Make the guide practical.</h2><p>Compare stays, check routes and build a first-pass itinerary with the trip builder.</p><Link className="button button-teal full-button" href="/plan-your-trip">Plan your trip <ArrowRight size={14} /></Link><Link className="button button-ghost button-dark full-button" href="/stay" style={{ marginTop: 8 }}>Browse stays <ArrowRight size={14} /></Link></aside></div></main></>;
}

export function TransfersPage() {
  const routes = [{ from: "Velana International Airport", to: "Maafushi", mode: "Shared speedboat", time: "35 min", price: "$35" }, { from: "Velana International Airport", to: "Baa Atoll", mode: "Seaplane", time: "30 min", price: "Request" }, { from: "Malé", to: "Dhigurah", mode: "Public ferry", time: "4 h 30", price: "$12" }, { from: "Velana International Airport", to: "North Malé Atoll", mode: "Private speedboat", time: "45 min", price: "$220 / boat" }];
  const [searched, setSearched] = useState(false);
  return <><PageIntro eyebrow="TRANSFERS" title="Make the journey part of the trip." description="Compare speedboats, public ferries and seaplanes by route, time and booking mode. Then arrive knowing what happens next." /><main className="page-main" data-reveal><div className="page-wrap"><div className="transfer-search detail-card"><div><span className="eyebrow">Route finder</span><h2>Where are you headed?</h2></div><div className="transfer-fields"><input className="input" placeholder="From · Airport or Malé" aria-label="Starting point" /><input className="input" placeholder="To · Island or resort" aria-label="Destination" /><button className="button button-teal" type="button" onClick={() => setSearched(true)}>{searched ? "Routes ready" : "Find a route"} <ArrowRight size={14} /></button></div>{searched && <div className="note-box route-note" role="status">We found sample routes below. Choose one to review timing, mode and booking notes.</div>}</div><div className="route-list">{routes.map((route) => <Link href="/transfers/airport-to-island" className="route-row" key={`${route.to}-${route.mode}`}><div><span className="eyebrow">{route.mode}</span><strong>{route.from} <span>→</span> {route.to}</strong></div><div><span>{route.time}</span><strong>{route.price}</strong></div><ArrowUpRight size={15} /></Link>)}</div><div className="note-box route-note">Seaplanes operate in daylight and are request-only. Public ferry schedules can change seasonally — confirm the latest departure before travelling.</div></div></main></>;
}

export function TripBuilder() {
  const [step, setStep] = useState(1);
  const [style, setStyle] = useState("Honeymoon");
  const styles = ["Honeymoon", "Family", "Budget", "Diving"];
  return <><PageIntro eyebrow="PLAN YOUR TRIP" title="Build the Maldives that fits you." description="Answer a few questions and we’ll shape a first-pass trip around your dates, travel style, budget and arrival." /><main className="page-main"><div className="page-wrap trip-builder"><div className="builder-progress"><span className={step >= 1 ? "active" : ""}>01</span><i /><span className={step >= 2 ? "active" : ""}>02</span><i /><span className={step >= 3 ? "active" : ""}>03</span></div>{step === 1 && <div className="builder-step"><span className="eyebrow">First, the feeling</span><h2>What kind of trip are you imagining?</h2><div className="style-grid">{styles.map((item) => <button key={item} className={`style-option ${style === item ? "selected" : ""}`} onClick={() => setStyle(item)}><span>{item === "Honeymoon" ? "✦" : item === "Family" ? "◒" : item === "Budget" ? "⌁" : "◌"}</span>{item}<small>{item === "Honeymoon" ? "Private, slow, special" : item === "Family" ? "Easy days for everyone" : item === "Budget" ? "More island, less fuss" : "Reef-first adventures"}</small></button>)}</div><button className="button button-teal" onClick={() => setStep(2)}>Continue <ArrowRight size={14} /></button></div>}{step === 2 && <div className="builder-step"><span className="eyebrow">Now, the details</span><h2>When will you be travelling?</h2><div className="builder-fields"><label className="field-label">Arrival date<input className="input" type="date" /></label><label className="field-label">Departure date<input className="input" type="date" /></label><label className="field-label">Travellers<select className="input" defaultValue="2"><option>2 travellers</option><option>3 travellers</option><option>4 travellers</option><option>5+ travellers</option></select></label></div><div className="builder-actions"><button className="button button-ghost button-dark" onClick={() => setStep(1)}>Back</button><button className="button button-teal" onClick={() => setStep(3)}>Show my trip <ArrowRight size={14} /></button></div></div>}{step === 3 && <div className="builder-step"><span className="eyebrow">Your first pass</span><h2>A {style.toLowerCase()} escape, starting here.</h2><div className="suggestion-plan"><div><span className="eyebrow">Stay</span><strong>{style === "Budget" ? "Coral Garden House" : "Overwater Romance"}</strong><p>South Ari · From ${style === "Budget" ? "92" : "480"} / night</p></div><div><span className="eyebrow">Transfer</span><strong>{style === "Budget" ? "Public ferry" : "Seaplane"}</strong><p>Route matched to your island</p></div><div><span className="eyebrow">Experience</span><strong>{style === "Diving" ? "Dive with manta rays" : "Sunset cruise"}</strong><p>Add it to your itinerary</p></div></div><div className="builder-actions"><button className="button button-ghost button-dark" onClick={() => setStep(2)}>Back</button><Link className="button button-sun" href="/stay">Browse matching stays <ArrowRight size={14} /></Link></div></div>}</div></main></>;
}

export function ContentPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <><PageIntro eyebrow={eyebrow} title={title} description={description} /><main className="page-main" data-reveal><div className="page-wrap content-page">{children}</div></main></>; }
